language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly
env:
    global:
        secure: "KsZ87L3slkuaiDdBR6UngTLwlu2FKH4STXZwnYqZ+oVSuA7mf3DtjSDBYi2cCWy75odnDfMozV+ryvnROD6Z/i/ferb7VXfKQkD9jC49KYhGLL2KBvEj+heXGZQOOSHH8mVonKDGaD4X0kiJlIyoNrJQeYZt0RKtOxDqDSfvaMk="
