language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    global:
        secure: "NrjNprAwPv1ECIpfttKtxkxUfH1tXucR0KJbj40pkjWp1cetYnYIkr97X8C4MO+4hnpur1woglSaas2eV9FcTz8m/pYj5cLzFmC9NnWhUR6J7He7ACHeUnQ8bbL1qKDBeiWYvbqG4jQD3c9aFrnWYptyOZ5yb55k0+dgEna4W9Y="

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - mkdir src
    - cp iterable.php src/iterable.php
    - cp iterableTest.php src/iterableTest.php
    - php vendor/bin/coveralls -v
